# Generated by Django 3.1.2 on 2022-01-09 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20220102_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='owners',
        ),
        migrations.AddField(
            model_name='chat',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_contact', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_owner', to='auth.user'),
            preserve_default=False,
        ),
    ]
